apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: rds-team-mydb-development
  namespace: rds-team
  labels:
    team: rds-team
    environment: development
    cost-center: eng-001
    managed-by: backstage
    provisioner: ack
spec:
  dbInstanceIdentifier: rds-team-mydb-development
  dbInstanceClass: db.t3.medium
  engine: postgres
  engineVersion: "15.17"
  masterUsername: appuser
  masterUserPassword:
    namespace: rds-team
    name: mydb-db-secret
    key: password
  allocatedStorage: 100
  storageType: gp3
  storageEncrypted: true
  multiAZ: false
  publiclyAccessible: false
  deletionProtection: false
  backupRetentionPeriod: 7
  dbSubnetGroupName: rds-team-mydb-development-subnet-group
  tags:
    - key: team
      value: rds-team
    - key: environment
      value: development
    - key: cost-center
      value: eng-001
    - key: managed-by
      value: backstage-ack
    - key: project
      value: mydb
