apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: team-c-webapp-development
  namespace: team-c
  labels:
    team: team-c
    environment: development
    cost-center: eng-001
    managed-by: backstage
    provisioner: ack
spec:
  name: team-c-webapp-development
  encryption:
    rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: aws:kms
  publicAccessBlock:
    blockPublicAcls: true
    blockPublicPolicy: true
    ignorePublicAcls: true
    restrictPublicBuckets: true
  tagging:
    tagSet:
      - key: team
        value: team-c
      - key: environment
        value: development
      - key: cost-center
        value: eng-001
      - key: managed-by
        value: backstage-ack
      - key: project
        value: webapp
