apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: platform-engineering-blog-platform-engineering-blog-590443650088-development-bucket
  description: "S3 bucket for platform-engineering-blog-590443650088 (development) — provisioned via Backstage/ACK"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/patel0ankur/idp-infra-configs/blob/main/teams/platform-engineering-blog/infra/s3-bucket.yaml"
    backstage.io/managed-by-origin-location: "url:https://github.com/patel0ankur/idp-infra-configs/blob/main/teams/platform-engineering-blog/infra/s3-bucket.yaml"
  labels:
    team: platform-engineering-blog
    environment: development
    cost-center: eng-001
    provisioner: ack
  tags:
    - s3
    - aws
    - ack
    - development
spec:
  type: s3-bucket
  owner: group:platform-engineering-blog
  lifecycle: production
  system: platform-engineering-blog-infrastructure
  dependencyOf: []
