apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: platform-engineering-blog-platform-engineering-blog-590443650088-development
  namespace: platform-engineering-blog
  labels:
    team: platform-engineering-blog
    environment: development
    cost-center: eng-001
    managed-by: backstage
    provisioner: ack
spec:
  name: platform-engineering-blog-platform-engineering-blog-590443650088-development
  
  versioningConfiguration:
    status: Enabled
  
  serverSideEncryptionConfiguration:
    rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: aws:kms
  publicAccessBlockConfiguration:
    blockPublicAcls: true
    blockPublicPolicy: true
    ignorePublicAcls: true
    restrictPublicBuckets: true
  tags:
    - key: team
      value: platform-engineering-blog
    - key: environment
      value: development
    - key: cost-center
      value: eng-001
    - key: managed-by
      value: backstage-ack
    - key: project
      value: platform-engineering-blog-590443650088
